 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 workflows:
   primary:
     jobs:
       - build:
          context: Common

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: msbuild ScintillaDiff/ScintillaDiff.csproj /t:restore
       - run: msbuild ScintillaDiff/ScintillaDiff.csproj /p:Configuration=Release
       - run: msbuild ScintillaDiff.SUO/ScintillaDiff.SUO.csproj /p:Configuration=Release
# No need for bleeding edge       - run: dotnet tool install --global PowerShell
       - run: 
          name: Push to NuGet
          command: |
            dotnet pack ScintillaDiff/ScintillaDiff.csproj -c:Release
            dotnet pack ScintillaDiff.SUO/ScintillaDiff.SUO.csproj -c:Release
            ScintillaDiff/NuGet-Push.ps1
            
